version: '3'

services:
  php:
    image: yiisoftware/yii2-php:8.0-fpm
    working_dir: /app
    volumes:
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
      - ./docker/php/.bashrc:/var/www/.bashrc
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
    depends_on:
      - db
      - mailcatcher
    restart: ${RESTART}

  api:
    image: nginx:1.15-alpine
    volumes:
      - ./docker/api/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    depends_on:
      - php
    restart: ${RESTART}
    labels:
      traefik.enable: "true"
      traefik.http.routers.api.rule: "Host(`api.${DOMAIN}`)"

    networks:
      - default
      - web

  backend:
    image: nginx:1.15-alpine
    volumes:
      - ./docker/backend/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    depends_on:
      - php
    restart: ${RESTART}
    labels:
      traefik.http.routers.backend.rule: "Host(`backend.${DOMAIN}`)"
      traefik.enable: "true"

    networks:
      - default
      - web

  frontend:
    image: nginx:1.15-alpine
    volumes:
      - ./docker/frontend/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/app:delegated
    depends_on:
      - php
    restart: ${RESTART}
    labels:
      traefik.http.routers.frontend.rule: "Host(`${DOMAIN}`)"
      traefik.enable: "true"

    networks:
      - default
      - web

  mailcatcher:
    image: jeanberu/mailcatcher:latest
    labels:
      traefik.enable: "true"
      traefik.http.services.mailcatcher-kit.loadbalancer.server.port: "1080"
      traefik.http.routers.mailcatcher-kit.rule: "Host(`mail.${DOMAIN}`)"
      traefik.http.routers.mailcatcher-kit.service: "mailcatcher-kit"
    networks:
      - default
      - web
    command: "mailcatcher --no-quit --foreground --ip=0.0.0.0 --smtp-port=${SMTP_PORT}"
    restart: ${RESTART}

  db:
    image: postgres:13.3-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./docker/db/initdb.d:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - 127.0.0.1:${DOCKER_DB_PORT}:5432
    restart: ${RESTART}
  traefik:
    image: "traefik:v2.8"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    restart: ${RESTART}

  php-worker:
    image: yiisoftware/yii2-php:7.1-fpm
    working_dir: /app
    volumes:
      - ~/.composer-docker/cache:/var/www/.composer/cache:delegated
      - ./:/app:delegated
      - ./docker/php/docker-php-entrypoint:/usr/local/bin/docker-php-entrypoint
    command: /usr/local/bin/php /app/yii queue/listen
    environment:
      PHP_USER_ID: ${PHP_USER_ID}
    depends_on:
      - db
      - mailcatcher
    restart: ${RESTART}

volumes:
  db_data:

networks:
  web:
    external: true
